version: "3.8"

services:

  app:
    build: .
    container_name: app
    environment:

    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src

  db:
    image: mysql
    container_name: db